#!/bin/sh

# get font and icon specifics from xresource file
VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "JetBrains Mono Medium 13")}
VALUE_COLOR=${color:-$(xrescat i3xrocks.value.color "#D8DEE9")}
LABEL_COLOR=${label_color:-$(xrescat i3xrocks.label.color "#7B8394")}
LABEL_ICON=${label_icon:-$(xrescat i3xrocks.label.todo " td")}

# format net usage output with fixed width
NT="$(printf "%2s" "$(td count)")"

# output net usage using pango markup
ICON_SPAN="<span color=\"${LABEL_COLOR}\">$LABEL_ICON</span>"
VALUE_SPAN="<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\"> $NT</span>"

echo "${ICON_SPAN}${VALUE_SPAN}"

if [ -n "$button" ]; then
    /usr/bin/i3-msg -q exec "/usr/bin/x-terminal-emulator -e td --interactive"
fi
